### ISSUE TITLE
Unhandled exception (#93f96601)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#162] opened 2018-02-23 02:47 UTC
```
Commix version: 2.3-dev#24
Python version: 2.7.14
Operating system: nt
Command line: commix.py -r C:\Users\Phil\Documents\BeeBox Files\os.txt

```
```
Traceback (most recent call last):
  File "C:\Users\Phil\commix\commix.py", line 31, in <module>
    import src.core.main
  File "C:\Users\Phil\commix\src\core\main.py", line 1081, in <module>
    parser.logfile_parser()
  File "C:\Users\Phil\commix\src\core\injections\controller\parser.py", line 87, in logfile_parser
    request = open(request_file, "r")
IOError: [Errno 13] Permission denied: 'C:\\Users\\Phil\\Documents\\BeeBox'
```

**Comment by stasinopoulos** [comment] 2018-02-23 05:39
Duplicate of https://github.com/commixproject/commix/issues/163

**Closed by stasinopoulos** 2018-02-23 05:39 UTC
