### ISSUE TITLE
Unhandled exception (#353ddd15)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#400] opened 2018-11-27 20:46 UTC
```
Commix version: 2.7-dev#41
Python version: 2.7.12
Operating system: posix
Command line: commix.py --url=************************************************ --technique=c --level=3 --referer=http://www.google.com.tr --user-agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 928, in <module>
    response, url = url_response(url)
  File "main.py", line 248, in url_response
    request = init_request(url)
  File "main.py", line 229, in init_request
    url = redirection.do_check(url)
  File "redirection.py", line 89, in do_check
    redirected_url = response.geturl()
AttributeError: 'NoneType' object has no attribute 'geturl'
```

**Comment by stasinopoulos** [comment] 2018-11-28 06:43
Duplicate of https://github.com/commixproject/commix/issues/395

**Closed by stasinopoulos** 2018-11-28 06:43 UTC
Labels: duplicate
