### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'Values' object has no attribute 'MULTI_TARGETS'"

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#758] opened 2022-04-16 10:22 UTC
```
Commix version: 3.5-dev#34
Python version: 3.6.9
Operating system: posix
Command line: commix.py --url=******************************* --level 3

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 806, in <module>
    if menu.options.MULTI_TARGETS:
AttributeError: 'Values' object has no attribute 'MULTI_TARGETS'
```

**Comment by stasinopoulos** [comment] 2022-04-16 14:18
Duplicate of https://github.com/commixproject/commix/issues/757

**Closed by stasinopoulos** 2022-04-16 14:18 UTC
