### ISSUE TITLE
Unhandled exception (#7e17f680)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#160] opened 2018-02-22 08:00 UTC
```
Commix version: 2.3-dev#40
Python version: 2.7.9
Operating system: posix
Command line: commix.py --url=************************************ --file-upload=/home/web.php --file-dest=/var/www/upload/image/

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1169, in <module>
    response, url = url_response(url)
  File "main.py", line 219, in url_response
    response = examine_request(request)
  File "main.py", line 113, in examine_request
    response = urllib2.urlopen(request)
  File "urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "urllib2.py", line 431, in open
    response = self._open(req, data)
  File "urllib2.py", line 449, in _open
    '_open', req)
  File "urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "httplib.py", line 1111, in getresponse
    response.begin()
  File "httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

**Comment by stasinopoulos** [comment] 2018-02-22 08:25
Duplicate of https://github.com/commixproject/commix/issues/126

**Closed by stasinopoulos** 2018-02-22 08:25 UTC
