### ISSUE TITLE
Unhandled exception (#fe58a98a)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#465] opened 2019-06-28 16:43 UTC
```
Commix version: 3.0-dev#2
Python version: 2.7.12
Operating system: posix
Command line: commix.py --url=******************************************************** --data=****** "ayush", "name": "test1", "service_type": "NGS","mas_instance_groups" :[ "ad708533-655a-4c91-bb15-c07d8c832a4b"], "reservation": {"resource_allocation_policy": {"instance_tag": "NGS"}}, "configuration": { "node_configuration": {"stylebook_info": {"version": "0.1", "namespace": "com.ngs.formsso.stylebooks", "name": "ngs-form-sso-config"}, "stylebook_configuration": {"logonformurl": "http://exchange2007.dnpg-blr.com/owa", "name": "ayush55", "userfield": "username", "priority": 65 , "passwdfield": "newpassword", "actionurl": "http://exchange2007.dnpg-blr.com/owa/auth/owaauth.dll"}}}} -H Content-Type:application/json -H Accept:application/json -H Cookie:NITRO_AUTH_TOKEN=##4653384BEEBD6F955DF94A4019E86905F2278A5F49150D62AB6255C1E746

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 885, in <module>
    main(filename, url)
  File "main.py", line 588, in main
    controller.do_check(url, filename)
  File "controller.py", line 605, in do_check
    perform_checks(url,filename)
  File "controller.py", line 528, in perform_checks
    basic_level_checks()
  File "controller.py", line 496, in basic_level_checks
    post_request(url, http_request_method, filename, timesec)
  File "controller.py", line 428, in post_request
    found_parameter = parameters.do_POST_check(parameter)
  File "parameters.py", line 292, in do_POST_check
    checks.is_empty(multi_parameters, http_request_method)
  File "checks.py", line 1103, in is_empty
    if len(multi_params[empty]) == 0:
TypeError: object of type 'int' has no len()
```

**Comment by stasinopoulos** [comment] 2019-06-28 16:45
Duplicate of https://github.com/commixproject/commix/issues/464

**Closed by stasinopoulos** 2019-06-28 16:45 UTC
Labels: duplicate
