### ISSUE TITLE
Bug Report: Unhandled exception "TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str." (#4c492144)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#832] opened 2023-05-12 03:30 UTC
```
Commix version: 3.7-stable
Python version: 3.9.0
Operating system: nt
Command line: commix.py -u *********************** -bin/voip_advanced1.asp --os=Unix --auth-url=http://192.168.1.1/cgi-bin/login.asp --auth-data=tatusActionFlag=&Auth_LoginID=admin&Auth_Password=Vnpt%401234 --proxy=http://172.24.96.1:8081 --data=******************************************************************************************** -9*%23%5D.T&megacodmstarttime=10&megacodmshorttime=3&megacodmlongtime=10&busytonetimer=40&hangingremindertimer=60&noanswertimer=60&dmtmode=0&polarityReversal=0&dtmfRelay=InBand&rfc2833pt=97&hookFlashRelay=None&transport=UDP&natKeepAliveTime=60&fromtoheadurl=0&optionssericemode=0&faxctrlmode=all&faxpassthru=PCMA&DivHotLineType=0&DivIsRegisterWithPort=Yes&DivIsMsgWithUser=0&DivHotLineActiveCode=&DivCWType=0&DivDialtone=Yes&DivCodecSelectFlag=0&DivDigitMatchMethod=2&DivSubscribeType=0&DivSubscribeExpire=86400&DivSupplementServiceType=1&EndCharacterHandleMode=0&comfortnoiseEnable=0&sendUnregister=YES&sessionTimer=&ses sionMinSE=&sessionRefresher=0&sessionMethod=0&dscpmark=46&mymgtos=46&VoIP_SIP_flag=1&natKeepAliveMessageFlag=0&changeCharEnableFlag=0&t38EnableFlag=0&echoCancelEnableFlag=Yes&comfortnoiseEnableFlag=1&vadEnableFlag=No&PrackEnableFlag=No&sendUnregisterFlag=Yes&AJBEnableFlag=1&sessiontimerEnableFlag=0&warmline0Flag=0&warmline1Flag=0&callwait0Flag=1&callwait1Flag=1&transfer0Flag=Yes&transfer1Flag=Yes&fwdAll0Flag=0&fwdAll1Flag=0&fwdBusy0Flag=0&fwdBusy1Flag=0&fwdNoAns0Flag=0&fwdNoAns1Flag=0&threepartyservice0Flag=Yes&threepartyservice1Flag=Yes&dndServiceFlag=1&dndStateFlag=0&dndActCodeFlag=N%2FA&dndDeActCodeFlag=N%2FA&synphonedate0Flag=1&synphonedate1Flag=1&endPointModeFlag=0&isMultiDigitMap=1&DigitMap1=%5B0-9*%23%5D.T&DigitMap2=&DigitMap3=N%2FA&DigitMap4=N%2FA&DigitMap5=N%2FA&DigitMap6=N%2FA&DigitMap7=N%2FA&DigitMap8=N%2FA&DigitMapEnableFlag=1&DigitMapSpecialEnableFlag=0&PBXPrefixEnableFlag=0&PBXDialSecondaryEnableFlag=0&echoCancelEnable=YES&AJBEnable=1&JBMaxLen=200&cb_DigitMapEnable=on&txt_DigitMap=%5B0-9*%23%5D.T&codecList2=1&codecList3=1&codecList4=2&codecList5=2&codecList6=3&codecList7=3&codecList0=4&codecList1=4&voicePtime0=20&voicePtime1=20&ingressGain0=0&ingressGain1=0&egressGain0=0&egressGain1=0&callwait0=on&callwait1=on&transfer0=on&transfer1=on&fwdNum0=&fwdNum1=&fwdNoAnsTime0=&fwdNoAnsTime1=&threepartyservice0=on&threepartyservice1=on&dndService=on&dndActiveCode=*26&dndDeActiveCode=%2326&endpointmode=0&calleridmode0=0&calleridmode1=0&minhookinterval0=300&minhookinterval1=300&maxhookinterval0=1100&maxhookinterval1=1100&minhookrelease0=1199&minhookrelease1=1199&synphonedate0=on&synphonedate1=on&txt_DigitMapSpecial=N%2FA&ipt_DigitMapSpecial=N%2FA&ipt_PBXPrefix=&CsrfToken=CVZX8Te8wHSYbXZ63OiqvT4ik44uL8ke --random-agent

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 805, in <module>
    main(filename, url)
  File "main.py", line 524, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 810, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 700, in perform_checks
    authentication.authentication_process()
  File "authentication.py", line 65, in authentication_process
    response = _urllib.request.urlopen(request, timeout=settings.TIMEOUT)
  File "request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "request.py", line 514, in open
    req = meth(req)
  File "request.py", line 1273, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
```

**Comment by stasinopoulos** [comment] 2023-05-12 06:31
Duplicate of https://github.com/commixproject/commix/issues/826. Update to the latest (dev) version.

**Closed by stasinopoulos** 2023-05-12 06:31 UTC
