### ISSUE TITLE
Unhandled exception (#2ef30ad8)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#210] opened 2018-04-24 07:25 UTC
```
Commix version: 2.4-dev#30
Python version: 2.7.15rc1
Operating system: posix
Command line: commix.py -u ********************************************************* -v 4 --level 3 --all

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1186, in <module>
    response, url = url_response(url)
  File "main.py", line 233, in url_response
    response = examine_request(request)
  File "main.py", line 108, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 202, in check_http_traffic
    http_response_content(response.read())
  File "headers.py", line 50, in http_response_content
    content = checks.remove_empty_lines(content)
  File "checks.py", line 103, in remove_empty_lines
    if content[0] == "\n":
IndexError: string index out of range
```

**Comment by stasinopoulos** [comment] 2018-04-25 04:33
Duplicate of https://github.com/commixproject/commix/issues/210

**Closed by stasinopoulos** 2018-04-25 04:33 UTC
Labels: duplicate
