### ISSUE TITLE
Unhandled exception (#b126279d)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#230] opened 2018-05-09 15:39 UTC
```
Commix version: 2.4-dev#40
Python version: 2.7.15rc1
Operating system: posix
Command line: commix.py -u *******************************
```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 41, in <module>
    from src.core.requests import tor
  File "tor.py", line 107
    if len(err_msg.line) > 2:
                            ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by stasinopoulos** [comment] 2018-05-09 15:42
Duplicate of https://github.com/commixproject/commix/issues/225

**Closed by stasinopoulos** 2018-05-09 15:42 UTC
Labels: duplicate
