### ISSUE TITLE
Unhandled exception (#da5e4d3b)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#197] opened 2018-04-09 12:40 UTC
```
Commix version: 2.3-stable
Python version: 2.7.14+
Operating system: posix
Command line: commix.py -u *****************
```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1178, in <module>
    response, url = url_response(url)
  File "main.py", line 229, in url_response
    response = examine_request(request)
  File "main.py", line 104, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 190, in check_http_traffic
    http_response_content(response.read())
  File "socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "httplib.py", line 1401, in read
    return s + self._file.read(amt - len(s))
  File "socket.py", line 384, in read
    data = self._sock.recv(left)
error: [Errno 104] Connection reset by peer
```

**Comment by stasinopoulos** [comment] 2018-04-09 15:33
Duplicate of https://github.com/commixproject/commix/issues/126

**Closed by stasinopoulos** 2018-04-09 15:33 UTC
