### ISSUE TITLE
Unhandled exception (#c8809f0e)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#602] opened 2021-02-16 08:58 UTC
```
Commix version: 3.2-dev#47
Python version: 3.9.1
Operating system: posix
Command line: commix.py --url=***************************************************************** --referer=http://parrot/commix-testbed/ --level=3

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 913, in <module>
    main(filename, url)
  File "main.py", line 627, in main
    controller.do_check(url, filename)
  File "controller.py", line 685, in do_check
    perform_checks(url,filename)
  File "controller.py", line 615, in perform_checks
    stored_http_header_injection(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 389, in stored_http_header_injection
    http_headers_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 348, in http_headers_injection
    user_agent_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 317, in user_agent_injection
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 299, in injection_proccess
    print(settings.print_warning_msg(warn_msg)) + Style.RESET_ALL
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by stasinopoulos** [comment] 2021-02-16 15:30
Duplicate of https://github.com/commixproject/commix/issues/590

**Closed by stasinopoulos** 2021-02-16 15:30 UTC
