### ISSUE TITLE
Unhandled exception (#10f00328)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#138] opened 2018-02-06 19:47 UTC
```
Commix version: 2.3-dev#29
Python version: 2.7.14+
Operating system: posix
Command line: commix.py --install

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 977, in <module>
    install.installer()
  File "install.py", line 76, in installer
    if not menu.options.batch:
NameError: global name 'menu' is not defined
```

**Comment by stasinopoulos** [comment] 2018-02-07 05:49
Duplicate of https://github.com/commixproject/commix/issues/115

**Closed by stasinopoulos** 2018-02-07 05:49 UTC
