### ISSUE TITLE
Unhandled exception (#313d9085)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#571] opened 2021-01-23 12:24 UTC
```
Commix version: 3.2-dev#46
Python version: 2.7.18
Operating system: posix
Command line: commix.py --url=************************************************* --cookie=***************************************************** _ga=GA1.2.189699999.1611216695; ASP.NET_SessionId=cn31odwudat04th44gxdvami; _gid=GA1.2.1497600273.1611396432; _gat_gtag_UA_178501015_1=1 --level=3 -v 3 -technique=t

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 910, in <module>
    response, url = url_response(url)
  File "main.py", line 319, in url_response
    response = examine_request(request)
  File "main.py", line 126, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 161, in check_http_traffic
    opener.open(request, timeout=settings.TIMEOUT)
  File "urllib2.py", line 429, in open
    response = self._open(req, data)
  File "urllib2.py", line 447, in _open
    '_open', req)
  File "urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "headers.py", line 139, in https_open
    self.do_open(connection, req)
  File "urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "httplib.py", line 1082, in request
    self._send_request(method, url, body, headers)
  File "httplib.py", line 1122, in _send_request
    self.endheaders(body)
  File "httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "httplib.py", line 894, in _send_output
    self.send(msg)
  File "headers.py", line 106, in send
    logs.log_traffic("-" * 37 + "\n" + info_msg + "\n" + "-" * 37)
NameError: free variable 'info_msg' referenced before assignment in enclosing scope
```

**Comment by stasinopoulos** [comment] 2021-01-23 14:39
Duplicate of https://github.com/commixproject/commix/issues/567

**Closed by stasinopoulos** 2021-01-23 14:39 UTC
Labels: duplicate
