### ISSUE TITLE
Bug Report: Unhandled exception "TypeError: 'str' object does not support item assignment" (#bf676fab)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#940] opened 2024-07-03 18:09 UTC
```
Commix version: 4.0-dev#23
Python version: 3.8.8
Operating system: posix
Command line: commix.py --url=****************************** --data=************************************************************************************************************************************************************************************************************************************************************************************** -p ************ 
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 866, in <module>
    main(filename, url, http_request_method)
  File "main.py", line 535, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 765, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 702, in perform_checks
    cookie_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 492, in cookie_injection
    cookie_parameters = parameters.do_cookie_check(menu.options.cookie)
  File "parameters.py", line 604, in do_cookie_check
    all_params[param] = ''.join(all_params[param]) + settings.INJECT_TAG
TypeError: 'str' object does not support item assignment
```

**Comment by stasinopoulos** [comment] 2024-07-04 05:39
Duplicate of https://github.com/commixproject/commix/issues/922

**Closed by stasinopoulos** 2024-07-04 05:39 UTC
