### ISSUE TITLE
Unhandled exception (#7cf336c8)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#447] opened 2019-04-29 12:20 UTC
```
Commix version: 2.8-stable
Python version: 2.7.16
Operating system: posix
Command line: commix.py -u ********************************************** --current-user --passwords

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 859, in <module>
    main(filename, url)
  File "main.py", line 576, in main
    controller.do_check(url, filename)
  File "controller.py", line 597, in do_check
    perform_checks(url,filename)
  File "controller.py", line 528, in perform_checks
    basic_level_checks()
  File "controller.py", line 493, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 411, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 114, in injection_proccess
    timesec, url_time_response = requests.estimate_response_time(url, timesec)
  File "requests.py", line 56, in estimate_response_time
    response = urllib2.urlopen(request)
  File "urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "urllib2.py", line 435, in open
    response = meth(req, response)
  File "urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "urllib2.py", line 651, in http_error_302
    fp.read()
  File "socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "httplib.py", line 633, in _read_chunked
    value.append(self._safe_read(amt))
  File "httplib.py", line 690, in _safe_read
    raise IncompleteRead(''.join(s), amt)
IncompleteRead: IncompleteRead(2533 bytes read, 5659 more expected)
```

**Comment by stasinopoulos** [comment] 2019-04-29 17:29
Duplicate of https://github.com/commixproject/commix/issues/438

**Closed by stasinopoulos** 2019-04-29 17:29 UTC
