### ISSUE TITLE
Unhandled exception (#9fbdb8b2)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#481] opened 2019-08-31 07:50 UTC
```
Commix version: 3.0-dev#32
Python version: 2.7.15
Operating system: posix
Command line: commix.py --url=*************************************************** --cookie=*************************************** PHPSESSID=2m0sper3sbom7dbejrlqqkb832 --shellshock

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 896, in <module>
    main(filename, url)
  File "main.py", line 593, in main
    controller.do_check(url, filename)
  File "controller.py", line 609, in do_check
    perform_checks(url,filename)
  File "controller.py", line 532, in perform_checks
    basic_level_checks()
  File "controller.py", line 497, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 415, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 104, in injection_proccess
    modules_handler.load_modules(url, http_request_method, filename)
  File "modules_handler.py", line 58, in load_modules
    shellshock.shellshock_handler(url, http_request_method, filename)
  File "shellshock.py", line 882, in shellshock_handler
    except _urllib.error.HTTPError as err_msg:
NameError: global name '_urllib' is not defined
```

**Comment by stasinopoulos** [comment] 2019-08-31 08:29
Duplicate of https://github.com/commixproject/commix/issues/480

**Closed by stasinopoulos** 2019-08-31 08:29 UTC
Labels: duplicate
