### ISSUE TITLE
Unhandled exception (#9ffa1867)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#220] opened 2018-04-30 12:24 UTC
```
Commix version: 2.4-dev#34
Python version: 2.7.15rc1
Operating system: posix
Command line: commix.py --url=************
```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1186, in <module>
    response, url = url_response(url)
  File "main.py", line 233, in url_response
    response = examine_request(request)
  File "main.py", line 108, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 198, in check_http_traffic
    response = urllib2.urlopen(request)
  File "urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "urllib2.py", line 435, in open
    response = meth(req, response)
  File "urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "urllib2.py", line 429, in open
    response = self._open(req, data)
  File "urllib2.py", line 447, in _open
    '_open', req)
  File "urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "urllib2.py", line 1241, in https_open
    context=self._context)
  File "urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "httplib.py", line 1121, in getresponse
    response.begin()
  File "httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by stasinopoulos** [comment] 2018-05-01 08:28
Duplicate of https://github.com/commixproject/commix/issues/206

**Closed by stasinopoulos** 2018-05-01 08:28 UTC
Labels: duplicate
