### ISSUE TITLE
Unhandled exception (#63839131)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#192] opened 2018-04-07 12:46 UTC
```
Commix version: 2.3-stable
Python version: 2.7.14+
Operating system: posix
Command line: commix.py -u ********************************************** --data=************** --technique=c

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1178, in <module>
    response, url = url_response(url)
  File "main.py", line 229, in url_response
    response = examine_request(request)
  File "main.py", line 104, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 186, in check_http_traffic
    response = urllib2.urlopen(request)
  File "urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "urllib2.py", line 429, in open
    response = self._open(req, data)
  File "urllib2.py", line 447, in _open
    '_open', req)
  File "urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "urllib2.py", line 1241, in https_open
    context=self._context)
  File "urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "httplib.py", line 1121, in getresponse
    response.begin()
  File "httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by stasinopoulos** [comment] 2018-04-08 07:59
Duplicate of https://github.com/commixproject/commix/issues/131

**Closed by stasinopoulos** 2018-04-08 07:59 UTC
