### ISSUE TITLE
Unhandled exception (#2efd2ca1)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#585] opened 2021-02-01 22:24 UTC
```
Commix version: 3.2-dev#50
Python version: 2.7.16
Operating system: posix
Command line: /usr/local/bin/commix

```
```
Traceback (most recent call last):
  File "/usr/local/bin/commix", line 35, in <module>
    main()
  File "/usr/local/bin/commix", line 30, in main
    import src.core.main
  File "main.py", line 651, in <module>
    common.days_from_last_update()
  File "common.py", line 34, in days_from_last_update
    days_from_last_update = int(time.time() - os.path.getmtime(settings.SETTINGS_PATH)) // (3600 * 24)
  File "genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'src/utils/settings.py'
```

**Comment by stasinopoulos** [comment] 2021-02-03 08:13
Duplicate of https://github.com/commixproject/commix/issues/570

**Closed by stasinopoulos** 2021-02-03 08:13 UTC
