### ISSUE TITLE
Unhandled exception (#b4c4ed56)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#381] opened 2018-11-01 17:30 UTC
```
Commix version: 2.7-dev#25
Python version: 2.7.11
Operating system: nt
Command line: commix.py -u *******************
```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1229, in <module>
    response, url = url_response(url)
  File "main.py", line 251, in url_response
    response = examine_request(request)
  File "main.py", line 109, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 167, in check_http_traffic
    opener.open(request)
  File "urllib2.py", line 423, in open
    protocol = req.get_type()
  File "urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: hhff.wanhaotz1.com
```

**Comment by stasinopoulos** [comment] 2018-11-03 07:51
Duplicate of https://github.com/commixproject/commix/issues/380

**Closed by stasinopoulos** 2018-11-03 07:51 UTC
