### ISSUE TITLE
Unhandled exception (#8c8b158a)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#458] opened 2019-06-11 11:42 UTC
```
Commix version: 2.9-dev#45
Python version: 2.7.16
Operating system: posix
Command line: commix.py -r -m xzqjx.txt

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 799, in <module>
    parser.logfile_parser()
  File "parser.py", line 70, in logfile_parser
    with open(request_file, 'r') as f:
IOError: [Errno 2] No such file or directory: '-m'
```

**Comment by stasinopoulos** [comment] 2019-06-12 05:10
Duplicate of https://github.com/commixproject/commix/issues/457

**Closed by stasinopoulos** 2019-06-12 05:10 UTC
