### ISSUE TITLE
Unhandled exception (#95647b60)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#579] opened 2021-01-27 05:53 UTC
```
Commix version: 3.2-dev#46
Python version: 3.6.9
Operating system: posix
Command line: commix.py -r **********
```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 910, in <module>
    response, url = url_response(url)
  File "main.py", line 319, in url_response
    response = examine_request(request)
  File "main.py", line 126, in examine_request
    headers.check_http_traffic(request)
  File "headers.py", line 161, in check_http_traffic
    opener.open(request, timeout=settings.TIMEOUT)
  File "request.py", line 526, in open
    response = self._open(req, data)
  File "request.py", line 544, in _open
    '_open', req)
  File "request.py", line 504, in _call_chain
    result = func(*args)
  File "headers.py", line 139, in https_open
    self.do_open(connection, req)
  File "request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "client.py", line 1292, in _send_request
    self.putrequest(method, url, **skips)
  File "client.py", line 1135, in putrequest
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/community/post_get?hash=1 HTTP/1.1' (found at least ' ')
```

**Comment by stasinopoulos** [comment] 2021-01-27 06:35
Duplicate of https://github.com/commixproject/commix/issues/568

**Closed by stasinopoulos** 2021-01-27 06:35 UTC
Labels: duplicate
