### ISSUE TITLE
Bug Report: Unhandled exception "AttributeError: 'NoneType' object has no attribute 'split'" (#05466946)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#907] opened 2024-04-18 17:57 UTC
```
Commix version: 4.0-dev#32
Python version: 3.10.12
Operating system: posix
Command line: commix.py -u **************** -old-but-gold.chals.io/cgi-bin/launch1.cgi --shellshock

```
```
Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 868, in <module>
    main(filename, url, http_request_method)
  File "main.py", line 524, in main
    controller.do_check(url, http_request_method, filename)
  File "controller.py", line 794, in do_check
    perform_checks(url, http_request_method, filename)
  File "controller.py", line 739, in perform_checks
    headers_checks(url, http_request_method, filename, timesec)
  File "controller.py", line 674, in headers_checks
    cookie_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 502, in cookie_injection
    cookie_parameters = parameters.do_cookie_check(menu.options.cookie)
  File "parameters.py", line 553, in do_cookie_check
    multi_parameters = cookie.split(settings.COOKIE_DELIMITER)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by stasinopoulos** [comment] 2024-04-18 19:26
Duplicate of https://github.com/commixproject/commix/issues/906

**Closed by stasinopoulos** 2024-04-18 19:26 UTC
