### ISSUE TITLE
Unhandled exception (#cf8f55a8)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#135] opened 2018-02-04 23:16 UTC
```
Commix version: 2.3-dev#27
Python version: 2.7.12
Operating system: posix
Command line: commix.py --purge-output

```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1160, in <module>
    response, url = url_response(url)
  File "main.py", line 202, in url_response
    url = checks.check_http_s(url)
  File "checks.py", line 380, in check_http_s
    if settings.PROXY_PROTOCOL in urlparse.urlparse(url).scheme:
  File "urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by stasinopoulos** [comment] 2018-02-05 05:59
Duplicate of https://github.com/commixproject/commix/issues/119

**Closed by stasinopoulos** 2018-02-05 05:59 UTC
