### ISSUE TITLE
Unhandled exception (#2fe8b4b5)

### ISSUE THREAD

**Issue by commixreporter** [commixproject/commix#361] opened 2018-09-02 19:42 UTC
```
Commix version: 2.5-stable
Python version: 2.7.15
Operating system: posix
Command line: commix.py -u **************
```
```
Traceback (most recent call last):
  File "commix.py", line 31, in <module>
    import src.core.main
  File "main.py", line 1208, in <module>
    response, url = url_response(url)
  File "main.py", line 245, in url_response
    request = init_request(url)
  File "main.py", line 222, in init_request
    request = urllib2.Request(url)
  File "urllib2.py", line 242, in __init__
    origin_req_host = request_host(self)
  File "urllib2.py", line 216, in request_host
    host = urlparse.urlparse(url)[1]
  File "urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "urlparse.py", line 191, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by stasinopoulos** [comment] 2018-09-02 19:44
Duplicate of https://github.com/commixproject/commix/issues/353

**Closed by stasinopoulos** 2018-09-02 19:44 UTC
Labels: duplicate
